name: Update specific section in README
on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행되도록 예약된 작업
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install github-api

    - name: Update specific section in README
      run: |
        GIST_ID="${{ secrets.GIST_ID }}"
        FILE_NAME="file-i-m-a-night"
        ACCESS_TOKEN="${{ secrets.GH_TOKEN }}"

        GIST_CONTENT=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/gists/$GIST_ID" | jq -r ".files.\"$FILE_NAME\".content")

        # 이 부분에서 README.md 파일의 특정 부분을 업데이트하는 스크립트를 작성
        # 예를 들어, sed 명령어를 사용하여 특정 문자열을 치환하는 방법:
        sed -i 's|<!-- GIST_CONTENT_START -->.*<!-- GIST_CONTENT_END -->|<!-- GIST_CONTENT_START -->'"$GIST_CONTENT"'<!-- GIST_CONTENT_END -->|' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update specific section in README"
        git push
