name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: Asia/Seoul
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_OS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          DEBUG_LOGGING: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
